### ISSUE TITLE
Getting data id signed url for job request returns null

### ISSUE THREAD

**Issue by hoddr** [voxel51/api-js#12]
```
> var ip = await v.jobs.RemoteDataPath.fromDataId('c89b7c0a-f646-47a3-b818-5e20a5c4e5c2')
> ip
RemoteDataPath {
  dataId: 'c89b7c0a-f646-47a3-b818-5e20a5c4e5c2',
  signedUrl: null }
```

**Comment by hoddr** [comment]
Also noting that this responsibility is taken care of server-side, correct?

**Comment by brimoor** [comment]
This is not a bug. `RemoteDataPath` is just a class that encapsulates the fact that we can specify the inputs to job requests either by dataId or signedURL.

**Comment by brimoor** [comment]
With that said, it's possible that we are not actually supporting signed URLs fully in our API. The idea was that we should allow users to "virtually" upload data by just specifying a signed URL that we would  use internally in lieu of actually storing the data in our cloud.

Are we supporting signed URLs as I described?

**Comment by brimoor** [comment]
Certainly we are not yet supporting data-as-signed-URLs via the console. The action item there would be to support pasting in a signed URL in the upload data dialog.

**Comment by brimoor** [comment]
Based on our discussion, I will remove support for signed URLs for now.
