### ISSUE TITLE
job.getJobRequest() returns null signed url field

### ISSUE THREAD

**Issue by hoddr** [voxel51/api-js#13]
```
> await api.getJobRequest('70529251-5658-4410-ad3a-cbc04fc4ea82')
JobRequest {
  analytic: 'video-formatter',
  inputs:
   { video:
      RemoteDataPath {
        dataId: 'c89b7c0a-f646-47a3-b818-5e20a5c4e5c2',
        signedUrl: null } },
  parameters: {} }
```

Noting again that the upload job request will not have a signed url field in its JSON representation.

**Comment by brimoor** [comment]
Also not a bug. If you issue `getJobRequest.toString()`, you'll see that it is constructing the job request JSON correctly.

**Comment by brimoor** [comment]
Based on our discussion, I will remove support for signed URLs for now.
